export const SERVICES = [
  "Tire Installation",
  "Tire Rotation",
  "Flat Tire Repair",
  "Wheel Alignment",
  "Brake Service",
  "Oil Change",
  "Battery Replacement",
  "Tune Up",
  "Timing Belt",
  "Struts & Shocks",
  "AC Service",
  "Engine & Transmission Rebuilds",
  "Lift Kits",
  "Lowering Kits",
  "Custom Work",
  "Multi-Point Inspection",
  "Other",
];

export const INSPECTION_PRESETS = [
  "Front brake pads",
  "Rear brake pads",
  "Front rotors",
  "Rear rotors",
  "Tire tread - LF",
  "Tire tread - RF",
  "Tire tread - LR",
  "Tire tread - RR",
  "Oil level",
  "Coolant level",
  "Transmission fluid",
  "Brake fluid",
  "Battery health",
  "Serpentine belt",
  "Air filter",
  "Cabin filter",
  "Wiper blades",
  "Headlights",
  "Tail lights",
  "Alignment",
  "Suspension",
  "Exhaust system",
  "AC system",
];

export const SHOP_INFO = {
  name: "Tires+ Complete Auto Service",
  phone: "530-342-8338",
  email: "tirespluschico@gmail.com",
  address: "624 Broadway St, Chico, CA 95928",
};
